# Generated by Django 5.0.2 on 2024-04-15 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppSite", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
